apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: metabase

patchesStrategicMerge:
- security-group-policy.patch.yaml
- service-account.patch.yaml
- database-secret.patch.yaml
- deployment.patch.yaml
